---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-demo-lb
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: 'demo.gauzy.co'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http' # http2
        # service.beta.kubernetes.io/do-loadbalancer-http2-ports: "443"
        # service.beta.kubernetes.io/do-loadbalancer-certificate-id: "gauzy.co"
        service.beta.kubernetes.io/do-loadbalancer-size-slug: 'lb-small'
        service.beta.kubernetes.io/do-loadbalancer-hostname: 'demo.gauzy.co'
spec:
    type: LoadBalancer
    selector:
        app: gauzy-demo-webapp
    ports:
        - name: http
          protocol: TCP
          port: 80 # 443
          targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-demo-api-lb
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: 'apidemo.gauzy.co'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http' # http2
        # service.beta.kubernetes.io/do-loadbalancer-http2-ports: "443,80"
        service.beta.kubernetes.io/do-loadbalancer-size-slug: 'lb-small'
        service.beta.kubernetes.io/do-loadbalancer-hostname: 'apidemo.gauzy.co'
spec:
    type: LoadBalancer
    selector:
        app: gauzy-demo-api
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-demo-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gauzy-demo-api
    template:
        metadata:
            labels:
                app: gauzy-demo-api
        spec:
            containers:
                - name: gauzy-demo-api
                  image: ghcr.io/ever-co/gauzy-api:latest
                  env:
                      - name: DEMO
                        value: true
                  ports:
                      - containerPort: 3000
                        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-demo-webapp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gauzy-demo-webapp
    template:
        metadata:
            labels:
                app: gauzy-demo-webapp
        spec:
            containers:
                - name: gauzy-demo-webapp
                  image: ghcr.io/ever-co/gauzy-webapp:latest
                  env:
                      - name: API_BASE_URL
                        value: 'http://apidemo.gauzy.co'
                      - name: DEMO
                        value: true
                  ports:
                      - containerPort: 4200
                        protocol: TCP
