name: Deploy to DigitalOcean

on:
    workflow_run:
        workflows: ['Build and Publish Docker Images']
        branches: [master]
        types:
            - completed

jobs:
    deploy-do:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 600

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ever

            - name: Apply k8s manifests changes in DigitalOcean k8s cluster (if any)
              run: |
                  kubectl --context do-sfo2-k8s-ever apply -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.demo.yaml
                  kubectl --context do-sfo2-k8s-ever apply -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.prod.yaml

            # we need this step because for now we just use :latest tag
            # note: for production we will use different strategy later
            - name: Restart Pods to pick up :latest tag version
              run: |
                  kubectl --context do-sfo2-k8s-ever rollout restart -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.demo.yaml
                  kubectl --context do-sfo2-k8s-ever rollout restart -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.prod.yaml
