name: Deploy to DigitalOcean

on:
    workflow_run:
        workflows: ['Build and Publish Docker Images']
        branches: [master]
        types:
            - completed

jobs:
    deploy-demo:
        runs-on: ubuntu-latest

        environment: demo

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 600

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ever

            - name: Apply k8s manifests changes in DigitalOcean k8s cluster (if any)
              run: |
                  kubectl --context do-sfo2-k8s-ever apply -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.demo.yaml

            # we need this step because for now we just use :latest tag
            # note: for production we will use different strategy later
            - name: Restart Pods to pick up :latest tag version
              run: |
                  kubectl --context do-sfo2-k8s-ever rollout restart deployment/gauzy-demo-api
                  kubectl --context do-sfo2-k8s-ever rollout restart deployment/gauzy-demo-webapp

    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
            uses: cypress-io/github-action@v2
            with:
                install: yarn bootstrap
                build: yarn build:package:all
                start: yarn start:api
                wait-on: 'http://localhost:3000/api'
                browser: chrome

    deploy-prod:
        runs-on: ubuntu-latest

        environment: prod

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 600

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ever

            - name: Apply k8s manifests changes in DigitalOcean k8s cluster (if any)
              run: |
                  kubectl --context do-sfo2-k8s-ever apply -f $GITHUB_WORKSPACE/.deploy/k8s/k8s-manifest.prod.yaml

            # we need this step because for now we just use :latest tag
            # note: for production we will use different strategy later
            - name: Restart Pods to pick up :latest tag version
              run: |
                  kubectl --context do-sfo2-k8s-ever rollout restart deployment/gauzy-prod-api
                  kubectl --context do-sfo2-k8s-ever rollout restart deployment/gauzy-prod-webapp
