name: Currents Cypress Tests
on:
    push:
        branches: [develop]
jobs:    
          
    e2e-tests:

        runs-on: [self-hosted]

        # we can try to run tests in the Docker containers later
        # container: cypress/browsers:node14.17.0-chrome88-ff89

        strategy:
          # when one test fails, DO NOT cancel the other
          # containers, because this will kill Cypress processes
          # leaving the Dashboard hanging ...
          # https://github.com/cypress-io/github-action/issues/48
          fail-fast: false

          matrix:
            # run copies of the current job in parallel on different runners
            containers: [1, 2]

        env:
          CYPRESS_CACHE_FOLDER: C:\Users\Evereq\AppData\Local\Cypress\Cache

          # We are using Currents Dashboard for now, but we can replace with our self-hosted if needed
          CYPRESS_API_URL: https://cy.currents.dev

          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}          

        timeout-minutes: 360

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                path: |                  
                  ~/.cache
                key: ${{ runner.os }}-cache-${{ hashFiles('yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cache-

            # - name: Increase file limit
            #  run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

            - name: Output build number
              run: echo "Running in Build ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}"

            - name: Add Yarn to path
              run: echo "C:\Users\Evereq\AppData\Roaming\npm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

            - name: Bootstrap Yarn
              run: yarn bootstrap

            - name: Build all packages
              run: yarn build:package:all

            - name: Install forever package
              run: npm install forever -g

            - name: Run API in background
              run: yarn start:api:forever

            - name: Run UI in background
              run: yarn start:gauzy:forever
                        
            - name: Install Cypress Package
              run: npm install -g cypress cy2 @currents/cli
            
            - name: Install Cypress for our e2e tests
              run: | 
                cd apps/gauzy-e2e
                yarn cypress install
            
            - name: Cypress info
              env:
                # make sure every Cypress install prints minimal information
                CI: 1
              # print Cypress and OS info
              run: |
                npx cypress verify
                npx cypress info
                npx cypress version
                npx cypress version --component package
                npx cypress version --component binary
                npx cypress version --component electron
                npx cypress version --component node

            - name: Currents Cypress run
              run: |
                until $(curl --output /dev/null --silent --head --fail http://localhost:3000/api); do
                  printf '.'
                  sleep 5
                done
                until $(curl --output /dev/null --silent --head --fail http://localhost:4200); do
                  printf '.'
                  sleep 5
                done
                
                currents run --parallel --record --key CURRENTS_CYPRESS_RECORD_KEY --ci-build-id "${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}" -C cypress.json -c "projectId=k1BPpu"



              
