name: Cypress Tests
on:
    push:
        branches: [develop]
jobs:    
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Increase file limit
              run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  working-directory: 'apps/gauzy-e2e'
                  install: yarn bootstrap
                  build: yarn build:package:all
                  start: yarn start:api
                  wait-on: 'http://localhost:3000/api'
                  browser: chrome