name: 'Check Spelling and Typos'
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
